//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchMaster
    {
        public float BatchID { get; set; }
        public string BatchName { get; set; }
        public Nullable<float> CourseID { get; set; }
        public Nullable<System.DateTime> BatchStartDate { get; set; }
        public Nullable<System.DateTime> BatchEndDate { get; set; }
        public Nullable<decimal> BatchFee { get; set; }
        public Nullable<int> BatchDiscPer { get; set; }
        public Nullable<System.TimeSpan> BatchStartTime { get; set; }
        public Nullable<System.TimeSpan> BatchEndTime { get; set; }
        public string BatchClass { get; set; }
        public string Remarks { get; set; }
        public Nullable<float> InstitutionID { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
    }
}
