//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseMaster
    {
        public float CourseID { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public string CoursePeriod { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<System.DateTime> CourseEndDate { get; set; }
        public Nullable<System.DateTime> CourseAdvtDate { get; set; }
        public string CourseAdvtPeriod { get; set; }
        public Nullable<float> InstitutionID { get; set; }
        public Nullable<System.TimeSpan> CourseHours { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public Nullable<int> Deleted { get; set; }
    }
}
