//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachersNotificationToStudent
    {
        public float TeacherTaskID { get; set; }
        public string TaskName { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
        public Nullable<System.TimeSpan> TaskTime { get; set; }
        public Nullable<float> BatchID { get; set; }
        public Nullable<int> SendStatus { get; set; }
        public Nullable<int> SentCount { get; set; }
        public string Remarks { get; set; }
        public Nullable<float> InstitutionID { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
    }
}
