//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadFile
    {
        public float UploadID { get; set; }
        public string UploadName { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string ViewGroup { get; set; }
        public string UploadFile1 { get; set; }
        public Nullable<float> InstitutionID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
    }
}
