//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public float UserID { get; set; }
        public string UserName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<float> CategoryID { get; set; }
        public Nullable<int> AdminStatus { get; set; }
        public Nullable<int> Active { get; set; }
        public string UserID1 { get; set; }
        public Nullable<float> InstitutionID { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<int> OTP { get; set; }
        public Nullable<int> OTPVerify { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RegistrationToken { get; set; }
    }
}
