//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBatchDetail
    {
        public float UserBatchDetID { get; set; }
        public Nullable<float> CourseID { get; set; }
        public Nullable<float> BatchID { get; set; }
        public Nullable<float> UserID { get; set; }
        public Nullable<float> CategoryID { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public Nullable<decimal> Disc { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
    }
}
